apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-flux
  annotations:
    provider: helm
spec:
  crossplane:
    version: ">=v1.8.0"
  dependsOn:
    - provider: crossplane/provider-helm
      version: "v0.10.0"
  # ignoreCrossplaneConstraints: false
  # package: ghcr.io/junaid18183/crossplane-config-flux:v0.0.2
  # packagePullPolicy: Always
  # revisionActivationPolicy: Automatic
  # revisionHistoryLimit: 1
  # skipDependencyResolution: false
