apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: flux.ijuned.com
spec:
  defaultCompositionRef:
    name: flux-helm
  group: ijuned.com
  names:
    kind: Flux
    plural: flux
  claimNames:
    kind: FluxClaim
    plural: fluxclaims
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy:
                    default: Delete
                    description: DeletionPolicy specifies what will happen to the underlying
                      external when this managed resource is deleted - either "Delete"
                      or "Orphan" the external resource.
                    enum:
                    - Orphan
                    - Delete
                    type: string
                  sourcecontroller_image:
                    description: image repo for the sourcecontroller
                    type: string
                    default: ghcr.io/fluxcd/source-controller
                  namespace:
                    description: Namespace to deploy the flux
                    type: string
                    default: flux-system
                  sourcecontroller_tag:
                    description: image repo for the sourcecontroller
                    type: string
                    default: v0.25.9
                  image_pull_secret:
                    description: Kubernetes secret name used for pulling the toolkit images from a private registry.
                    type: string
                    default: ""
              kubeConfig:
                description: The Kubeconfig details.
                type: object
                properties:
                  secretNamespace:
                    description: Namespace of secret
                    type: string
                    default: crossplane-system
                  secretName:
                    description: secretName
                    type: string
                  secretKey:
                    description: secretKey
                    type: string
                    default: kubeconfig
            required:
            - kubeConfig
          status:
            type: object
            properties:
              version:
                description: The installed version of the Flux
                type: string
    additionalPrinterColumns:
    - name: version
      type: string
      jsonPath: ".status.version"