name: CI

on:
  push:
    branches:
      - main
      - release-*
      - v0.0.2
  workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      # The tagger step uses the same logic in the build submodule to generate package tag
      # https://github.com/upbound/build/blob/4f64913157a952dbe77cd9e05457d9abe695a1d4/makelib/common.mk#L193
      - name: Set tag
        run: echo "::set-output name=VERSION_TAG::$(git describe --dirty --always --tags | sed 's/-.*//' )"
        id: tagger
      - name: Build
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          channel: stable
          version: current
          command : build configuration -f ${{ github.workspace }}/package/ --name flux-package.xpkg
      - name: Install Up crossplane cli and Push Package
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh -x
          mv kubectl-crossplane /usr/local/bin
          kubectl crossplane --help
          #login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          kubectl crossplane push configuration -f package.xpkg ush configuration -f package/flux-package.xpkg  ghcr.io/junaid18183/crossplane-config-flux:${{ steps.tagger.outputs.VERSION_TAG }}